# DFD Docker Environment
#
# Inspired by <https://github.com/martin-helmich/docker-typo3>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

version: "3"
services:
  dfd-typo3:
    image: registry.gitlab.rlp.net/adwmainz/digicademy/dfd/dfd-docker/dfd-typo3
    container_name: dfd_typo3
    restart: always
    environment:
      - "UID=${UID:-33}"
      - "GID=${GID:-33}"
      - "TZ=${TIMEZONE:-UTC}"
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    extra_hosts:
      - "${HOSTNAME:-localhost}:127.0.0.1"
    volumes:
      - "./apache2/ssl:/etc/apache2/ssl"
      - "./composer:/var/www/html/composer"
      - "./scripts:/var/www/html/scripts"
      - "./vendor:/var/www/html/vendor"
      - "${HTDOCS:-./htdocs}:/var/www/html/htdocs"
    networks:
      - dfd
  dfd-database:
    image: mariadb:10.9
    container_name: dfd_database
    restart: always
    command:
      - --sql_mode=NO_ENGINE_SUBSTITUTION
    environment:
      - "TZ=${TIMEZONE:-UTC}"
      - "MYSQL_USER=${DBUSER}"
      - "MYSQL_PASSWORD=${DBPASSWORD}"
      - "MYSQL_DATABASE=${DBNAME}"
      - "MYSQL_ROOT_PASSWORD=${DBROOT_PASSWORD}"
    volumes:
      - "./mysql/db:/var/lib/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
    networks:
      - dfd
  dfd-search:
    image: macbre/sphinxsearch:3.0.1
    container_name: dfd_search
    restart: always
    volumes:
      - ./sphinxsearch/conf:/opt/sphinx/conf
      - ./sphinxsearch/index:/opt/sphinx/index
    networks:
      - dfd
  dfd-postfix:
    image: juanluisbaptiste/postfix:latest
    container_name: dfd_postfix
    restart: always
    expose:
      - "25"
    env_file:
      - .env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - dfd

networks:
  dfd:
