# DFD Docker Compose
# Copyright (C) 2023 Jonatan Jalle Steller <jonatan.steller@adwmainz.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Inspired by <https://github.com/martin-helmich/docker-typo3> and
# previous Digicademy Docker setups.

version: "3"
services:
  dfd-webserver:
    image: registry.gitlab.rlp.net/adwmainz/digicademy/dfd/dfd_docker/dfd_webserver
    container_name: dfd_webserver
    restart: always
    environment:
      - "UID=${UID:-33}"
      - "GID=${GID:-33}"
      - "TZ=${TIMEZONE:-UTC}"
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    extra_hosts:
      - "${HOSTNAME:-localhost}:127.0.0.1"
    volumes:
      - "./config/apache2/ssl:/etc/apache2/ssl"
      - "${HTDOCS:-./dfd}:/var/www/html/dfd"
    networks:
      - dfd
  dfd-database:
    image: mariadb:10
    container_name: dfd_database
    restart: always
    command:
      - --sql_mode=NO_ENGINE_SUBSTITUTION
    environment:
      - "TZ=${TIMEZONE:-UTC}"
      - "MYSQL_USER=${DBUSER}"
      - "MYSQL_PASSWORD=${DBPASSWORD}"
      - "MYSQL_DATABASE=${DBNAME}"
      - "MYSQL_ROOT_PASSWORD=${DBROOT_PASSWORD}"
    volumes:
      - "./mariadb/db:/var/lib/mysql"
      - "./mariadb/conf:/etc/mysql/conf.d"
    networks:
      - dfd
#  dfd-search:
#    image: manticoresearch/manticore:6.2.12
#    container_name: dfd_search
#    restart: always
#    ports:
#      - "9306:9306"
#      - "9308:9308"
#    ulimits:
#      nproc: 65535
#      nofile:
#         soft: 65535
#         hard: 65535
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - ./manticore/data:/var/lib/manticore
#      - ./manticore/manticore.conf:/etc/manticoresearch/manticore.conf
#    networks:
#      - dfd
  dfd-postfix:
    image: juanluisbaptiste/postfix:latest
    container_name: dfd_postfix
    restart: always
    expose:
      - "25"
    env_file:
      - .env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - dfd

networks:
  dfd:
