# This file is part of the CHF Container environment.
#
# For the full copyright and license information, please read the
# LICENSE.txt file that was distributed with this source code.

# Get slim Debian with PHP 8.3 FPM
FROM docker.io/library/php:8.3-fpm

# Install extra packages
RUN apt-get update && apt-get install -y --no-install-recommends \
        curl \
        cron \
        git \
        gnupg \
        htop \
        locales-all \
        ssh-client \
        vim \
        wget \
        ghostscript \
        exiftool \
        imagemagick

# Install necessary PHP modules
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions \
    && install-php-extensions \
        @composer \
        exif \
        gd \
        intl \
        opcache \
        pdo_mysql \
        xsl \
        zip

# Use production-ready default PHP config
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Create empty config folder for PHP Composer owned by user www-data
RUN mkdir -p /var/www/.composer && \
    chown 33:33 /var/www/.composer

# Add ImageMagick config for user www-data to handle PDF and Illustrator files
RUN mkdir -p /var/www/.config && \
    mkdir -p /var/www/.config/ImageMagick && \
    echo '<policymap>\n    <policy domain="coder" rights="read" pattern="{PDF,AI}" />\n</policymap>' > /var/www/.config/ImageMagick/policy.xml && \
    chmod 0644 /var/www/.config/ImageMagick/policy.xml && \
    chown -R 33:33 /var/www/.config
