# This file is part of the CHF Container environment.
#
# For the full copyright and license information, please read the
# LICENSE.txt file that was distributed with this source code.

# Get slim Debian with PHP 8.3 FPM
FROM docker.io/library/php:8.3-fpm

# Install extra packages
RUN apt-get update && apt-get install -y --no-install-recommends \
        curl \
        git \
        gnupg \
        htop \
        locales-all \
        ssh-client \
        vim \
        wget \
        ghostscript \
        exiftool \
        imagemagick

# Install necessary PHP modules
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions \
    && install-php-extensions \
        @composer \
        gd \
        intl \
        opcache \
        pdo_mysql \
        xsl \
        zip

# Use the production-ready default PHP config
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini" \
    && echo "expose_php = Off" >> "$PHP_INI_DIR/php.ini" \
    && echo "html_errors = Off" >> "$PHP_INI_DIR/php.ini" \
    && echo "log_errors = ${PHP_LOG_ERRORS}" >> "$PHP_INI_DIR/php.ini" \
    && echo "memory_limit = ${PHP_MEMORY_LIMIT}" >> "$PHP_INI_DIR/php.ini" \
    && echo "max_execution_time = ${PHP_MAX_EXECUTION_TIME}" >> "$PHP_INI_DIR/php.ini" \
    && echo "upload_max_filesize = ${PHP_UPLOAD_MAX_FILESIZE}" >> "$PHP_INI_DIR/php.ini" \
    && echo "post_max_size = ${PHP_POST_MAX_SIZE}" >> "$PHP_INI_DIR/php.ini" \
    && echo "allow_url_fopen = ${PHP_ALLOW_URL_FOPEN}" >> "$PHP_INI_DIR/php.ini" \
    && echo "max_input_vars = 3000" >> "$PHP_INI_DIR/php.ini" \
    && echo "always_populate_raw_post_data = -1" >> "$PHP_INI_DIR/php.ini"

# Retrieve PHP packages and TYPO3 languages
#WORKDIR /var/www/html
#RUN composer update && \
#    typo3 language:update
