# This file is part of the CHF Container environment.
#
# For the full copyright and license information, please read the
# LICENSE.txt file that was distributed with this source code.

# Get slim Debian with PHP 8.2 FPM
FROM docker.io/library/php:8.2-fpm

# Install required packages and PHP extensions
RUN apt-get update && apt-get install -y --no-install-recommends \
        bzip2 \
        curl \
        git \
        gnupg \
        htop \
        locales-all \
        ssh-client \
        vim \
        wget \
        ghostscript \
        exiftool \
        imagemagick \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
        apcu \
        bcmath \
        bz2 \
        gd \
        imagick \
        intl \
        ldap \
        memcached \
        opcache \
        pdo_mysql \
        soap \
        uploadprogress \
        xdebug \
        xmlrpc \
        xsl \
        zip

# Install PHP Composer
COPY --from=docker.io/composer/composer:2-bin /composer /usr/bin/composer

# Retrieve PHP packages and TYPO3 languages
#RUN composer update && \
#    typo3 language:update
