# This file is part of the CHF Container environment.
#
# For the full copyright and license information, please read the
# LICENSE.txt file that was distributed with this source code.

# Get slim Debian with Apache httpd
FROM docker.io/library/httpd:2.4

# Install required packages and PHP extensions
RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        htop \
        locales-all \
        ssh-client \
        vim \
        wget

# Enable required Apache modules by uncommenting them
RUN sed -i \
    # Enable compression
    -e '/#LoadModule deflate_module/s/^#//g' \
    # Enable expire headers
    -e '/#LoadModule expires_module/s/^#//g' \
    # Enable manipulating headers
    -e '/#LoadModule headers_module/s/^#//g' \
    # Enable assigning mime types
    -e '/#LoadModule mime_module/s/^#//g' \
    # Enable proxying capabilities
    -e '/#LoadModule proxy_module/s/^#//g' \
    # Enable FastCGI proxying
    -e '/#LoadModule proxy_fcgi_module/s/^#//g' \
    # Enable URL rewrites
    -e '/#LoadModule rewrite_module/s/^#//g' \
    # Enable SSL capabilities
    -e '/#LoadModule ssl_module/s/^#//g' \
    /usr/local/apache2/conf/httpd.conf

# Include custom virtual host configuration file in main Apache config
RUN echo "Include /usr/local/apache2/conf/extra/apache.vhost.conf" >> /usr/local/apache2/conf/httpd.conf
