base: 'http://namenforschung.local/'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=2'
  -
    errorCode: 503
    errorHandler: Page
    errorContentSource: 't3://page?uid=3'
languages:
  -
    title: 'Digitales Familiennamenwörterbuch Deutschlands'
    enabled: true
    base: /
    typo3Language: default
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: ''
    hreflang: de-DE
    direction: ''
    flag: de
    languageId: 0
rootPageId: 1
websiteTitle: ''
